export const UrlPath = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public`;

export const QueryKeyString = {
  current: "current",
  projet: "projet",
  team: "team",
  members: "members",
  Wmembers: "Wmembers",
  accompaniments: "accompaniments",
  accompanist: "accompanist",
  maps: "maps",
  purchase: "purchase",
  planning: "planning",
  rapports: "rapports",
  vt: "vt",
  conflits: "conflits",
  rencontre: "rencontre",
  Oneaccompanist: "Oneaccompanist",
  profile: "profile",
  chat: "chat",
  mychat: "mychat",
  usersNotInChat: "usersNotInChat",
  messages: "messages",
  admins: "admins",
  trainers: "trainers",
  notification: "notification",
  leaves: "leaves",
  DashboardStats: "DashboardStats",
  statsData: "statsData",
  SatsProjectUsers: "SatsProjectUsers",
  Activities: "Activities",
  classes: "classes",
  employes: "employes",
  akis:"akis"
};

export const Days = [
  "Dimanche",
  "Lundi",
  "Mardi",
  "Mercredi",
  "Jeudi",
  "Vendredi",
  "Samedi",
];

export const month = [
  "Janvier",
  "Février",
  "Mars",
  "Avril",
  "Mai",
  "Juin",
  "Juillet",
  "Août",
  "Septembre",
  "Octobre",
  "Novembre",
  "Décembre",
];
